# Custom config for myotube dataset finetuning
# Based on Swin-Base config with modifications for single-class dataset
# 
# SMALL DATASET ADJUSTMENTS (23 images total):
# - Training: 800 iterations = ~100 epochs (batch size 3)
# - Using training data for validation (no separate test set)  
# - Evaluation every ~12 epochs to monitor progress

_BASE_: configs/coco/instance-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Use your pre-trained model instead of default weights
  WEIGHTS: "model_final_54b88a.pkl"
  
  SEM_SEG_HEAD:
    # Change number of classes from 80 (COCO) to 1 (myotube)
    NUM_CLASSES: 1
  
  # Keep the Swin transformer backbone settings from the base config

# Dataset configuration 
DATASETS:
  TRAIN: ("myotube_train",)
  # No separate test set - using training data for validation
  TEST: ("myotube_train",)

# Solver configuration for finetuning
SOLVER:
  IMS_PER_BATCH: 3  # Reduced batch size for single GPU training
  BASE_LR: 0.00005  # Lower learning rate for finetuning (half of original)
  MAX_ITER: 800       # ~100 epochs (800 รท 8 iterations per epoch = 100 epochs)
  STEPS: (480, 720)   # LR drops at 60% and 90% of training
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 16  # 2 epochs for warmup (2 * 8 iterations = 16)
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1  # Keep backbone learning rate lower
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration with enhanced augmentations
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.5      # More conservative scaling for biological images
  MAX_SCALE: 1.5      # Avoid extreme scaling that might distort cell shapes
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
  
  # Additional augmentations
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.8, 1.0]    # Random crop between 80-100% of image
  
  # Color augmentations (good for microscopy images)
  COLOR_AUG_SSD: True
  
  # Horizontal flip (since myotubes can be oriented any way)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration
TEST:
  EVAL_PERIOD: 100   # Evaluate every ~12 epochs (100 รท 8 iterations per epoch)

# Data loader configuration
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2  # Reduced for single GPU

# Output directory
OUTPUT_DIR: "./output_myotube"

VERSION: 2 