# Stage 1 Panoptic Configuration: Algorithmic Annotations Training
# Based on Swin-Base panoptic config optimized for large dataset with algorithmic annotations
# 
# STAGE 1 DATASET: ~100 images with algorithmic annotations from batch processing
# - Training: 6000 iterations for robust feature learning
# - Conservative learning rate for stable training on noisy annotations
# - Focus on learning general myotube features and background separation

_BASE_: configs/coco/panoptic-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Use COCO pre-trained weights for initialization
  WEIGHTS: "model_final_54b88a_panoptic.pkl"
  
  SEM_SEG_HEAD:
    # Two classes: myotube (thing) + background (stuff)
    NUM_CLASSES: 2
  
  # Optimize for dense overlapping structures
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.3  # Lower threshold for algorithmic annotations
      OVERLAP_THRESHOLD: 0.0  # Zero overlap - each myotube is completely distinct
      PANOPTIC_ON: True
      INSTANCE_ON: False  # Disable instance evaluation for panoptic training
      SEMANTIC_ON: False  # Disable semantic evaluation - we don't have sem_seg ground truth

# Dataset configuration for Stage 1 (algorithmic annotations)
DATASETS:
  TRAIN: ("myotube_stage1_panoptic_train",)
  TEST: ("myotube_stage1_panoptic_val",)

# Stage 1 Solver: Optimized for 90 algorithmic images + 10 validation
SOLVER:
  IMS_PER_BATCH: 2  # Increase batch size for better gradient estimates
  BASE_LR: 0.00005  # Higher LR for faster convergence with small dataset
  MAX_ITER: 4500    # Optimized for 90 images: ~50 epochs at batch=2
  STEPS: (3000, 4200) # LR drops at 67% and 93%
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 300  # Longer warmup for stability with high-res images
  WEIGHT_DECAY: 0.01  # Lower weight decay for small dataset to prevent underfitting
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.2  # Allow backbone to adapt more to myotube structures
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1  # Less aggressive clipping for better learning
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration optimized for 9000×9000 myotube images
INPUT:
  IMAGE_SIZE: 1500  # Standard size for efficient training while preserving detail
  MIN_SCALE: 0.5    # Wider scale range to handle various myotube densities
  MAX_SCALE: 2.0    # Allow significant zoom to capture fine structures
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_panoptic_lsj"
  
  # Aggressive augmentations to compensate for small dataset size
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.5, 1.0]  # More aggressive cropping for better generalization
  
  # Conservative color augmentation for biological image integrity
  COLOR_AUG_SSD: True
  
  # All orientations (myotubes in all directions in the image)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration
TEST:
  EVAL_PERIOD: 225  # Evaluate every ~10 epochs (4500/20 steps per epoch)

# Data loader configuration  
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4  # More workers for higher batch size

# Output directory for Stage 1 panoptic
OUTPUT_DIR: "./output_stage1_panoptic_algorithmic"

VERSION: 2 