# Stage 1 Configuration: Algorithmic Annotations Training
# Based on Swin-Base config optimized for large dataset with algorithmic annotations
# 
# STAGE 1 DATASET: ~100 images with algorithmic annotations from batch processing
# - Training: 3000 iterations for robust feature learning
# - Conservative learning rate for stable training on noisy annotations
# - Focus on learning general myotube features

_BASE_: configs/coco/instance-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Use COCO pre-trained weights for initialization
  WEIGHTS: "model_final_83d103.pkl"
  
  SEM_SEG_HEAD:
    # Single class: myotube
    NUM_CLASSES: 1
  
  # Optimize for dense overlapping myotube structures
  MASK_FORMER:
    # Enhanced loss weights for overlapping structures
    DEEP_SUPERVISION: True
    CLASS_WEIGHT: 2.0    # Higher class weight for better myotube vs background
    MASK_WEIGHT: 25.0    # Higher mask weight for precise myotube boundaries
    DICE_WEIGHT: 2.0     # Dice loss for overlapping structures
    
    TEST:
      OBJECT_MASK_THRESHOLD: 0.25  # Lower threshold for thin/dim myotubes


# Dataset configuration for Stage 1 (algorithmic annotations)
DATASETS:
  TRAIN: ("myotube_stage1_train",)
  TEST: ("myotube_stage1_val",)

# Stage 1 Solver: Optimized for 4x training data (360 crops from 90 images)
SOLVER:
  IMS_PER_BATCH: 1  # Single image batch for A40 GPU memory constraints
  BASE_LR: 0.00002  # Stable LR for extended training with 4x data
  MAX_ITER: 18000   # 4x increase: 360 crops ร 50 epochs = 18,000 iterations
  STEPS: (12600, 16200)  # LR drops at 70% and 90% of 18,000 iterations
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 500   # Extended warmup for longer training
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1  # Keep backbone learning conservative
  CHECKPOINT_PERIOD: 1000  # Less frequent checkpoints for longer training
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration optimized for algorithmic annotations
INPUT:
  IMAGE_SIZE: 1500  # Match original image resolution for detail preservation
  MIN_SCALE: 0.8    # Conservative scaling to preserve thin myotube structures
  MAX_SCALE: 1.2    # Reduced range to avoid distorting elongated structures
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
  
  # OPTIMIZED: Larger crops for better myotube connectivity context
  CROP:
    ENABLED: True
    TYPE: "relative_range" 
    SIZE: [0.2, 0.3]  # Larger crops to capture full myotube structures and overlaps
  
  # Enhanced augmentations for dense overlapping myotubes
  COLOR_AUG_SSD: True  # Helps with varying fluorescence intensity
  
  # Horizontal and vertical flip (myotubes oriented in all directions)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration  
TEST:
  EVAL_PERIOD: 1800  # Evaluate every 50 epochs (18000 iter รท 360 crops = 50 epochs)

# Data loader configuration
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4

# Output directory for Stage 1
OUTPUT_DIR: "./output_stage1_algorithmic"

VERSION: 2 