# Configuration for Stage 1: Algorithmic Panoptic Training
# Based on Swin-Base with optimized settings for myotube segmentation

_BASE_: configs/coco/panoptic-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

MODEL:
  # Load pre-trained panoptic model
  WEIGHTS: "model_final_54b88a_panoptic.pkl"
  
  SEM_SEG_HEAD:
    # Two classes: myotube (thing) + background (stuff)
    NUM_CLASSES: 2
    IGNORE_VALUE: 255  # Explicit ignore value for crop constraint

  # Optimize for dense overlapping myotube structures
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.3
      OVERLAP_THRESHOLD: 0.0
      PANOPTIC_ON: True
      INSTANCE_ON: False
      SEMANTIC_ON: False
    # ADDED for stable learning
    DEEP_SUPERVISION: True
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    NO_OBJECT_WEIGHT: 0.1

# Dataset configuration for Stage 1 (algorithmic annotations)
DATASETS:
  TRAIN: ("myotube_stage1_panoptic_train",)
  TEST: ("myotube_stage1_panoptic_val",)

# Stage 1 Solver: Optimized for 90 algorithmic images + 10 validation
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00001
  MAX_ITER: 4500
  # ADJUSTED decay steps for longer training
  STEPS: (3150, 4050)
  WARMUP_ITERS: 300
  WEIGHT_DECAY: 0.01
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  # ADDED for memory efficiency
  AMP:
    ENABLED: True

# Input settings optimized for 9000×9000 myotube fluorescence images
# NEW: CROP-FIRST-THEN-SCALE approach for maximum detail preservation
INPUT:
  # Use MaskFormer dataset mapper with crop-first modification
  DATASET_MAPPER_NAME: "mask_former_panoptic"
  
  # CROP FIRST: Extract regions from full 9000×9000 resolution
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    # REFINED for large images
    SIZE: [0.5, 1.0]
  
  # THEN SCALE: Multi-scale training on the cropped regions
  MIN_SIZE_TRAIN: [800, 960, 1200]
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  
  # Data augmentation optimized for fluorescence images
  COLOR_AUG_SSD: True
  RANDOM_FLIP: "horizontal"
  FORMAT: "RGB"
  
  # Critical missing parameters for mask_former_panoptic mapper
  SIZE_DIVISIBILITY: 32

# Evaluation settings
TEST:
  # ADJUSTED to match longer training
  EVAL_PERIOD: 500

# Data loading
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4

# Output directory for Stage 1 panoptic
OUTPUT_DIR: "./output_stage1_panoptic_algorithmic"

VERSION: 2 