# Stage 1 Configuration: Algorithmic Annotations Training
# Based on Swin-Base config optimized for large dataset with algorithmic annotations
# 
# STAGE 1 DATASET: ~100 images with algorithmic annotations from batch processing
# - Training: 3000 iterations for robust feature learning
# - Conservative learning rate for stable training on noisy annotations
# - Focus on learning general myotube features

_BASE_: configs/coco/instance-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Use COCO pre-trained weights for initialization
  WEIGHTS: "model_final_83d103.pkl"
  
  SEM_SEG_HEAD:
    # Single class: myotube
    NUM_CLASSES: 1
  
  # Optimize for dense overlapping structures
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.3  # Lower threshold for thin structures
      OVERLAP_THRESHOLD: 0.0  # Zero overlap - each myotube is completely distinct

# Dataset configuration for Stage 1 (algorithmic annotations)
DATASETS:
  TRAIN: ("myotube_stage1_train",)
  TEST: ("myotube_stage1_val",)

# Stage 1 Solver: Conservative settings for algorithmic annotations
SOLVER:
  IMS_PER_BATCH: 1  # Single image batch for A40 GPU memory constraints
  BASE_LR: 0.00003  # Slightly increased LR for more efficient training
  MAX_ITER: 5000    # Optimized for ~100 images with batch size 1
  STEPS: (3500, 4500)  # LR drops at 70% and 90%
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 150   # Longer warmup for single-image training
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1  # Keep backbone learning conservative
  CHECKPOINT_PERIOD: 500  # Save checkpoint every evaluation for best model selection
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration optimized for algorithmic annotations
INPUT:
  IMAGE_SIZE: 1500  # Match original image resolution for detail preservation
  MIN_SCALE: 0.8    # Conservative scaling to preserve thin myotube structures
  MAX_SCALE: 1.2    # Reduced range to avoid distorting elongated structures
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
  
  # Conservative augmentations for algorithmic annotations
  CROP:
    ENABLED: True
    TYPE: "relative_range" 
    SIZE: [0.15, 0.25]  # Very minimal cropping to preserve full myotube lengths
  
  # Minimal color augmentation (algorithms may be sensitive to color changes)
  COLOR_AUG_SSD: False
  
  # Horizontal and vertical flip (myotubes oriented in all directions)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration
TEST:
  EVAL_PERIOD: 500  # Evaluate every 50 epochs (5000 iter รท 100 images = 50 epochs)

# Data loader configuration
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4

# Output directory for Stage 1
OUTPUT_DIR: "./output_stage1_algorithmic"

VERSION: 2 