# FIXED Stage 1 Panoptic Config - Addresses all identified training issues
# Root cause: Loss weights and learning rate schedule were broken

MODEL:
  META_ARCHITECTURE: "MaskFormer"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  # Use COCO pre-trained weights for better initialization
  WEIGHTS: "model_final_54b88a_panoptic.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 2  # myotube + background
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    # CRITICAL FIX: Proper loss weights for class imbalance (10.8% myotubes vs 89.2% background)
    NO_OBJECT_WEIGHT: 0.01      # Much lower weight for background class
    CLASS_WEIGHT: 10.0          # Higher classification weight
    MASK_WEIGHT: 20.0           # MUCH higher mask loss weight (was causing zero loss)
    DICE_WEIGHT: 20.0           # MUCH higher dice loss weight (was causing zero loss)
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      OBJECT_MASK_THRESHOLD: 0.1  # Lower threshold to detect more myotubes
      OVERLAP_THRESHOLD: 0.0
      PANOPTIC_ON: True
      INSTANCE_ON: False
      SEMANTIC_ON: False

DATASETS:
  TRAIN: ("myotube_stage1_panoptic_train",)
  TEST: ("myotube_stage1_panoptic_val",)

# CRITICAL FIX: Proper learning rate schedule
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002             # Higher base LR
  STEPS: (1500, 2500)         # Much later LR decay (was dropping too early!)
  MAX_ITER: 3000              # More iterations for proper learning
  WARMUP_FACTOR: 0.001        # Proper warmup
  WARMUP_ITERS: 300           # Longer warmup
  WEIGHT_DECAY: 0.01          # Lower weight decay
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0           # Higher clip value for stable training
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 500

# Optimized input pipeline
INPUT:
  DATASET_MAPPER_NAME: "mask_former_panoptic"
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.3, 1.0]          # Allow larger crops
    SINGLE_CATEGORY_MAX_AREA: 0.6  # Ensure myotubes present in crops
  MIN_SIZE_TRAIN: [800, 900, 1000, 1100, 1200]
  MAX_SIZE_TRAIN: 1400
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  COLOR_AUG_SSD: True
  RANDOM_FLIP: "horizontal"
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "TrainingSampler"

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: "./output_stage1_panoptic_fixed"