# Stage 1 Panoptic Configuration: Algorithmic Annotations Training
# Based on Swin-Base panoptic config optimized for large dataset with algorithmic annotations
# 
# STAGE 1 DATASET: ~100 images with algorithmic annotations from batch processing
# - Training: 6000 iterations for robust feature learning
# - Conservative learning rate for stable training on noisy annotations
# - Focus on learning general myotube features and background separation

_BASE_: configs/coco/panoptic-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Use COCO pre-trained weights for initialization
  WEIGHTS: "model_final_54b88a_panoptic.pkl"
  
  SEM_SEG_HEAD:
    # Single class: myotube (background is implicit, ID 0)
    NUM_CLASSES: 1
  
  # Optimize for dense overlapping structures
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.3  # Lower threshold for algorithmic annotations
      OVERLAP_THRESHOLD: 0.0  # Zero overlap - each myotube is completely distinct
      PANOPTIC_ON: True
      INSTANCE_ON: True   # Enable instance evaluation  
      SEMANTIC_ON: False  # Disable semantic evaluation - we don't have sem_seg ground truth

# Dataset configuration for Stage 1 (algorithmic annotations)
DATASETS:
  TRAIN: ("myotube_stage1_panoptic_train",)
  TEST: ("myotube_stage1_panoptic_val",)

# Stage 1 Solver: Conservative settings for noisy algorithmic data
SOLVER:
  IMS_PER_BATCH: 1  # Single image batch for A40 memory constraints
  BASE_LR: 0.00002  # Conservative LR for single-image batches and noisy data
  MAX_ITER: 6000    # Extended training for single-image batches
  STEPS: (4000, 5500) # LR drops at 67% and 92% 
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 150  # Extended warmup for single-image training
  WEIGHT_DECAY: 0.05  # Higher weight decay for noisy data regularization
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1  # Conservative backbone learning for stable training
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01  # Conservative gradient clipping for stability
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration optimized for large algorithmic dataset
INPUT:
  IMAGE_SIZE: 1500  # Match batch processing output resolution
  MIN_SCALE: 0.8    # Moderate scaling for data augmentation
  MAX_SCALE: 1.2    # Balanced scaling range
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_panoptic_lsj"
  
  # Conservative augmentations for preserving algorithmic annotation integrity
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.8, 1.0]  # Minimal cropping to preserve myotube connectivity
  
  # Conservative color augmentation for biological image integrity
  COLOR_AUG_SSD: True
  
  # All orientations (myotubes in all directions in the image)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration
TEST:
  EVAL_PERIOD: 100  # Evaluation every 750 iterations (~125 epochs for 100 images)

# Data loader configuration  
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2  # Balanced for single-image batches

# Output directory for Stage 1 panoptic
OUTPUT_DIR: "./output_stage1_panoptic_algorithmic"

VERSION: 2 