# Clean Stage 1 Panoptic Config - No ResNet conflicts
# Pure Swin Transformer configuration for myotube segmentation

MODEL:
  META_ARCHITECTURE: "MaskFormer"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "swin_base_patch4_window12_384.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 2  # myotube + background
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9  # 9 decoder layers
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      OBJECT_MASK_THRESHOLD: 0.3
      OVERLAP_THRESHOLD: 0.0

DATASETS:
  TRAIN: ("myotube_stage1_panoptic_train",)
  TEST: ("myotube_stage1_panoptic_val",)

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  STEPS: (700, 900)
  MAX_ITER: 1000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 100
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

INPUT:
  DATASET_MAPPER_NAME: "mask_former_panoptic"
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.4, 1.0]
    SINGLE_CATEGORY_MAX_AREA: 0.7
  MIN_SIZE_TRAIN: [800, 900, 1000, 1100, 1200, 1300]
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  COLOR_AUG_SSD: True
  RANDOM_FLIP: "horizontal"
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "TrainingSampler"

TEST:
  EVAL_PERIOD: 200

OUTPUT_DIR: "./output_stage1_panoptic_algorithmic"