# Stage 2 Configuration: Manual Annotations Fine-tuning
# Fine-tuning config for high-quality manual annotations
# 
# STAGE 2 DATASET: 7 images with high-quality manual annotations  
# - Training: 1400 iterations for precise fine-tuning (200 epochs × 7 images)
# - Optimized learning rate for effective adaptation to manual annotations
# - Loads weights from Stage 1 checkpoint

_BASE_: configs/coco/instance-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Will be set dynamically to Stage 1 checkpoint
  WEIGHTS: ""  # Set by training script to stage1 checkpoint
  
  SEM_SEG_HEAD:
    # Single class: myotube  
    NUM_CLASSES: 1
  
  # Fine-tuned settings for precise manual annotations
  MASK_FORMER:
    # Preserve Stage 1 loss weights (don't change what works)
    DEEP_SUPERVISION: True
    CLASS_WEIGHT: 2.0    # Keep Stage 1 settings
    MASK_WEIGHT: 25.0    # Keep Stage 1 settings  
    DICE_WEIGHT: 2.0     # Keep Stage 1 settings
    
    TEST:
      OBJECT_MASK_THRESHOLD: 0.3  # Slightly higher than Stage 1 for precision

# Dataset configuration for Stage 2 (manual annotations)
DATASETS:
  TRAIN: ("myotube_stage2_train",)
  TEST: ("myotube_stage2_val",)

# Stage 2 Solver: Fine-tuning settings for 4x training data (28 crops from 7 images)
SOLVER:
  IMS_PER_BATCH: 1  # Single image batch (optimized for memory)
  BASE_LR: 0.00004  # Conservative LR for fine-tuning from improved Stage 1
  MAX_ITER: 5000    # 4x increase: 28 crops × 180 epochs = ~5,000 iterations
  STEPS: (3500, 4500) # LR drops at 70% and 90% of 5,000 iterations
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 200   # Extended warmup for longer training
  WEIGHT_DECAY: 0.01  # Reduced weight decay for fine-tuning
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.05  # Slightly higher - can learn more since Stage 1 is better
  CHECKPOINT_PERIOD: 1000  # Save checkpoints every evaluation period
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.005  # Slightly relaxed clipping for better adaptation
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration optimized for manual annotations
INPUT:
  IMAGE_SIZE: 1500  # Match original resolution for precise manual annotations
  MIN_SCALE: 0.9    # Very conservative scaling for precise manual boundaries
  MAX_SCALE: 1.1    # Minimal scaling to preserve manual annotation precision
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
  
  # CONSISTENT: Use same crop size as Stage 1 for transfer learning
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.2, 0.3]  # Same as Stage 1 - important for consistent feature learning
  
  # Conservative augmentations to preserve manual annotation precision
  COLOR_AUG_SSD: True  # Mild color augmentation for fluorescence variations
  
  # All orientations (myotubes in all directions in the image)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration  
TEST:
  EVAL_PERIOD: 1000  # Evaluate every 36 epochs (5000 iter ÷ 28 crops × 36 = 1000 iterations)

# Data loader configuration
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 1  # Single worker for high-res images to avoid memory issues

# Output directory for Stage 2
OUTPUT_DIR: "./output_stage2_manual"

VERSION: 2 