# Stage 2 Configuration: Manual Annotations Fine-tuning
# Fine-tuning config for high-quality manual annotations
# 
# STAGE 2 DATASET: ~5 images with high-quality manual annotations
# - Training: 1000 iterations for precise fine-tuning
# - Higher learning rate for effective adaptation to manual annotations
# - Loads weights from Stage 1 checkpoint

_BASE_: configs/coco/instance-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Will be set dynamically to Stage 1 checkpoint
  WEIGHTS: ""  # Set by training script to stage1 checkpoint
  
  SEM_SEG_HEAD:
    # Single class: myotube  
    NUM_CLASSES: 1
  
  # Fine-tuned settings for precise manual annotations
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200  # Match Stage 1 for consistency
    TEST:
      OBJECT_MASK_THRESHOLD: 0.4  # Higher threshold for quality manual annotations
      OVERLAP_THRESHOLD: 0.5  # Stricter overlap for precise segmentation

# Dataset configuration for Stage 2 (manual annotations)
DATASETS:
  TRAIN: ("myotube_stage2_train",)
  TEST: ("myotube_stage2_val",)

# Stage 2 Solver: Fine-tuning settings for manual annotations
SOLVER:
  IMS_PER_BATCH: 1  # Single image batch for 1500x1500 high-resolution fine-tuning
  BASE_LR: 0.00008  # Slightly lower LR for high-res dense structures
  MAX_ITER: 1500    # More iterations for complex dense manual annotations
  STEPS: (1000, 1300) # LR drops at 67% and 87%
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 30  # Longer warmup for high-res manual data
  WEIGHT_DECAY: 0.01  # Reduced weight decay for fine-tuning
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.03  # Very conservative backbone for precise tuning
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.003  # Very small gradient clipping for precise tuning
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration optimized for manual annotations
INPUT:
  IMAGE_SIZE: 1500  # Match original resolution for precise manual annotations
  MIN_SCALE: 0.9    # Very conservative scaling for precise manual boundaries
  MAX_SCALE: 1.1    # Minimal scaling to preserve manual annotation precision
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
  
  # Enhanced but careful augmentations for manual annotations
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.85, 1.0]  # Moderate cropping while preserving myotube connectivity
  
  # Mild color augmentation to preserve manual annotation integrity
  COLOR_AUG_SSD: True
  
  # All orientations (myotubes in all directions in the image)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration  
TEST:
  EVAL_PERIOD: 300  # Balanced evaluation frequency for high-res manual data

# Data loader configuration
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 1  # Single worker for high-res images to avoid memory issues

# Output directory for Stage 2
OUTPUT_DIR: "./output_stage2_manual"

VERSION: 2 