# Configuration for Stage 2: Manual Panoptic Fine-tuning
# Based on Swin-Base fine-tuning on high-quality manual annotations

_BASE_: configs/coco/panoptic-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Will be set programmatically to Stage 1 checkpoint
  WEIGHTS: ""
  
  SEM_SEG_HEAD:
    # Two classes: myotube (thing) + background (stuff)
    NUM_CLASSES: 2
    IGNORE_VALUE: 255  # Explicit ignore value for crop constraint
  
  # Fine-tuned settings for precise manual annotations
  MASK_FORMER:

    DEEP_SUPERVISION: True
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    NO_OBJECT_WEIGHT: 0.1
    
    TEST:
      OBJECT_MASK_THRESHOLD: 0.5
      OVERLAP_THRESHOLD: 0.0
      PANOPTIC_ON: True
      INSTANCE_ON: False
      SEMANTIC_ON: False

# Dataset configuration for Stage 2 (manual annotations)
DATASETS:
  TRAIN: ("myotube_stage2_panoptic_train",)
  TEST: ("myotube_stage2_panoptic_val",)

# Fine-tuning hyperparameters - Stage 2 (manual data)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00001
  MAX_ITER: 500
  STEPS: (350, 450)
  WARMUP_ITERS: 25
  WEIGHT_DECAY: 0.005
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 100
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input settings optimized for 9000×9000 myotube fluorescence images
# NEW: CROP-FIRST-THEN-SCALE approach for maximum detail preservation
INPUT:
  DATASET_MAPPER_NAME: "mask_former_panoptic"
  
  # CROP FIRST: More conservative for precious manual annotations
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    # REFINED for high-quality manual data
    SIZE: [0.2, 1.0]
  
  # THEN SCALE: Multi-scale training on the cropped regions
  MIN_SIZE_TRAIN: [800, 1000, 1200, 1400]
  MAX_SIZE_TRAIN: 1800
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  
  # Minimal augmentation for high-quality manual data
  COLOR_AUG_SSD: True      # Light augmentation for fluorescence robustness
  RANDOM_FLIP: "horizontal"
  FORMAT: "RGB"
  
  # Critical parameters for mask_former_panoptic mapper
  SIZE_DIVISIBILITY: 32

# Evaluation settings
TEST:
  EVAL_PERIOD: 100         # Evaluate every 100 iterations (~20 epochs)

# Data loading
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2

# Output directory for Stage 2 panoptic
OUTPUT_DIR: "./output_stage2_panoptic_manual"

VERSION: 2 