# Configuration for Stage 1: Algorithmic Panoptic Training
# Based on Swin-Base with optimized settings for myotube segmentation

_BASE_: configs/coco/panoptic-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

MODEL:
  # Load pre-trained panoptic model
  WEIGHTS: "model_final_54b88a_panoptic.pkl"
  
  SEM_SEG_HEAD:
    # Two classes: myotube (thing) + background (stuff)
    NUM_CLASSES: 2
    IGNORE_VALUE: 255  # Explicit ignore value for crop constraint

  # Optimize for dense overlapping myotube structures
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.3  # Lower threshold for algorithmic annotations
      OVERLAP_THRESHOLD: 0.0  # Zero overlap - each myotube is completely distinct
      PANOPTIC_ON: True
      INSTANCE_ON: False  # Disable instance evaluation for panoptic training
      SEMANTIC_ON: False  # Disable semantic evaluation - we don't have sem_seg ground truth

# Dataset configuration for Stage 1 (algorithmic annotations)
DATASETS:
  TRAIN: ("myotube_stage1_panoptic_train",)
  TEST: ("myotube_stage1_panoptic_val",)

# Stage 1 Solver: Optimized for 90 algorithmic images + 10 validation
SOLVER:
  IMS_PER_BATCH: 2          # Small batch for 9000x9000 images
  BASE_LR: 0.00005          # Higher LR for algorithmic data
  MAX_ITER: 4500            # ~90 images × 50 epochs
  STEPS: (3000, 4200)       # LR decay at 67%, 93%
  WARMUP_ITERS: 300         # Extended warmup
  WEIGHT_DECAY: 0.01        # Moderate regularization
  BACKBONE_MULTIPLIER: 0.2  # Faster backbone learning
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1         # Higher clip value for large crops
    NORM_TYPE: 2.0

# Input settings optimized for 9000×9000 myotube fluorescence images
# NEW: CROP-FIRST-THEN-SCALE approach for maximum detail preservation
INPUT:
  # Use MaskFormer dataset mapper with crop-first modification
  DATASET_MAPPER_NAME: "mask_former_panoptic"
  
  # CROP FIRST: Extract regions from full 9000×9000 resolution
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.4, 1.0]       # 1800×1800 to 9000×9000 crops - HUGE scale diversity!
    SINGLE_CATEGORY_MAX_AREA: 1.0  # Allow myotubes to fill crop area
  
  # THEN SCALE: Multi-scale training on the cropped regions
  MIN_SIZE_TRAIN: [800, 900, 1000, 1100, 1200, 1300]  # Multi-scale for cropped regions
  MAX_SIZE_TRAIN: 1500      # Max dimension after scaling
  MIN_SIZE_TRAIN_SAMPLING: "choice"  # Random choice each epoch
  
  # Data augmentation optimized for fluorescence images
  COLOR_AUG_SSD: True      # Enable for better generalization of fluorescence intensity
  RANDOM_FLIP: "horizontal"
  FORMAT: "RGB"
  
  # Critical missing parameters for mask_former_panoptic mapper
  SIZE_DIVISIBILITY: 32    # Required for proper model input processing

# Evaluation settings
TEST:
  EVAL_PERIOD: 225         # Evaluate every 225 iterations (~5 epochs)

# Data loading
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4  # More workers for higher batch size

# Output directory for Stage 1 panoptic
OUTPUT_DIR: "./output_stage1_panoptic_algorithmic"

VERSION: 2 