# Configuration for Stage 2: Manual Panoptic Fine-tuning
# Based on Swin-Base fine-tuning on high-quality manual annotations

_BASE_: configs/coco/panoptic-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Will be set programmatically to Stage 1 checkpoint
  WEIGHTS: ""
  
  SEM_SEG_HEAD:
    # Two classes: myotube (thing) + background (stuff)
    NUM_CLASSES: 2
    IGNORE_VALUE: 255  # Explicit ignore value for crop constraint
  
  # Fine-tuned settings for precise manual annotations
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.5  # Balanced threshold for manual annotations
      OVERLAP_THRESHOLD: 0.0  # Zero overlap - each myotube is completely distinct
      PANOPTIC_ON: True   # Enable panoptic evaluation
      INSTANCE_ON: False  # Disable instance evaluation for panoptic training
      SEMANTIC_ON: False  # Disable semantic evaluation - we don't have sem_seg ground truth

# Dataset configuration for Stage 2 (manual annotations)
DATASETS:
  TRAIN: ("myotube_stage2_panoptic_train",)
  TEST: ("myotube_stage2_panoptic_val",)

# Fine-tuning hyperparameters - Stage 2 (manual data)
SOLVER:
  IMS_PER_BATCH: 1          # Very small batch for limited manual data
  BASE_LR: 0.00001          # Very low LR for fine-tuning
  MAX_ITER: 500             # ~5 images × 100 epochs
  STEPS: (350, 450)         # LR decay at 70%, 90%
  WARMUP_ITERS: 25          # Short warmup for fine-tuning
  WEIGHT_DECAY: 0.005       # Lower regularization for small dataset
  BACKBONE_MULTIPLIER: 0.1  # Slow backbone adaptation
  CHECKPOINT_PERIOD: 1000   # Save checkpoint every 1000 iterations
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01        # Conservative gradient clipping for fine-tuning
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True           # Memory efficiency for large crops

# Input settings optimized for 9000×9000 myotube fluorescence images
# NEW: CROP-FIRST-THEN-SCALE approach for maximum detail preservation
INPUT:
  # Use MaskFormer dataset mapper with crop-first modification
  DATASET_MAPPER_NAME: "mask_former_panoptic"
  
  # CROP FIRST: More conservative for precious manual annotations
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.2, 1.0]       # 2700×2700 to 9000×9000 crops - preserve more context for manual data
    SINGLE_CATEGORY_MAX_AREA: 1.0  # Allow myotubes to fill crop area
  
  # THEN SCALE: Multi-scale training on the cropped regions
  MIN_SIZE_TRAIN: [800, 900, 1000, 1100, 1200, 1300]  # Multi-scale for cropped regions
  MAX_SIZE_TRAIN: 1500      # Max dimension after scaling
  MIN_SIZE_TRAIN_SAMPLING: "choice"  # Random choice each epoch
  
  # Minimal augmentation for high-quality manual data
  COLOR_AUG_SSD: True      # Light augmentation for fluorescence robustness
  RANDOM_FLIP: "horizontal"
  FORMAT: "RGB"
  
  # Critical parameters for mask_former_panoptic mapper
  SIZE_DIVISIBILITY: 32    # Required for proper model input processing

# Evaluation settings
TEST:
  EVAL_PERIOD: 100         # Evaluate every 100 iterations (~20 epochs)

# Data loading
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2  # Reduced workers for memory management with high-res images

# Output directory for Stage 2 panoptic
OUTPUT_DIR: "./output_stage2_panoptic_manual"

VERSION: 2 