# Stage 2 Panoptic Configuration: Manual Annotations Fine-tuning
# Fine-tuning panoptic config for high-quality manual annotations
# 
# STAGE 2 DATASET: ~2 images with high-quality manual annotations  
# - Training: 400 iterations for precise fine-tuning
# - Higher learning rate for effective adaptation to manual annotations
# - Loads weights from Stage 1 panoptic checkpoint

_BASE_: configs/coco/panoptic-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml

# Model configuration
MODEL:
  # Will be set dynamically to Stage 1 panoptic checkpoint
  WEIGHTS: ""  # Set by training script to stage1 panoptic checkpoint
  
  SEM_SEG_HEAD:
    # Two classes: myotube (thing) + background (stuff)
    NUM_CLASSES: 2
  
  # Fine-tuned settings for precise manual annotations
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.4  # Higher threshold for quality manual annotations
      OVERLAP_THRESHOLD: 0.0  # Zero overlap - each myotube is completely distinct
      PANOPTIC_ON: True   # Enable panoptic evaluation
      INSTANCE_ON: False  # Disable instance evaluation for panoptic training
      SEMANTIC_ON: False  # Disable semantic evaluation - we don't have sem_seg ground truth

# Dataset configuration for Stage 2 (manual annotations)
DATASETS:
  TRAIN: ("myotube_stage2_panoptic_train",)
  TEST: ("myotube_stage2_panoptic_val",)

# Stage 2 Solver: Fine-tuning settings for manual annotations (5 images)
SOLVER:
  IMS_PER_BATCH: 1  # Single image batch for careful fine-tuning
  BASE_LR: 0.00001  # Lower LR for stable fine-tuning from Stage 1 weights
  MAX_ITER: 500     # Optimized for 5 images: ~100 epochs (5 images × 100 = 500 iter)
  STEPS: (350, 450) # LR drops at 70% and 90% of 500 iterations
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 25  # Minimal warmup for fine-tuning
  WEIGHT_DECAY: 0.005  # Very low weight decay to preserve learned features
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1  # Allow moderate backbone adaptation to high-quality data
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01  # Gentle gradient clipping
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# Input configuration optimized for 5 high-quality manual annotations
INPUT:
  IMAGE_SIZE: 1500  # Consistent with Stage 1 for transfer learning
  MIN_SCALE: 0.8    # Moderate scaling to leverage manual precision
  MAX_SCALE: 1.3    # Allow some variation while preserving fine detail
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_panoptic_lsj"
  
  # Conservative augmentations to preserve manual annotation quality
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.5, 1.0]  # Moderate cropping for generalization without losing structure
  
  # Light color augmentation for robustness
  COLOR_AUG_SSD: True
  
  # All orientations (myotubes in all directions in the image)
  RANDOM_FLIP: "horizontal"

# Evaluation configuration  
TEST:
  EVAL_PERIOD: 100  # Evaluate every ~20 epochs (500/5 steps per epoch)

# Data loader configuration
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 1  # Single worker for high-res images to avoid memory issues

# Output directory for Stage 2 panoptic
OUTPUT_DIR: "./output_stage2_panoptic_manual"

VERSION: 2 